server:
  port: 8081

product:
  message: Product service configuration loaded from Config Server [Dev]

feature:
  product-cache-enabled: true

service:
  timeout:
    connection: 2000
    read: 5000